In [116]:
import boto3
import pandas as pd
import numpy as np
import io
import torch
from sklearn.preprocessing import MinMaxScaler

In [117]:
s3_client = boto3.client(
    's3', 
    endpoint_url='http://localstack:4566',
    # Como é LocalStack, podemos passar credenciais falsas qualquer
    aws_access_key_id='test',
    aws_secret_access_key='test',
    region_name='us-east-1'
)

bucket_name = 'data-extract'
archive_path = 'landing/01-07-2026/raw_PETR4.csv'

try:
    print(f"Baixando arquivo {archive_path} do bucket {bucket_name}...")
    # Recuperamos o arquivo do S3
    response = s3_client.get_object(Bucket=bucket_name, Key=archive_path)
    
    # Lemos o conteúdo do arquivo CSV em um DataFrame do Pandas
    bytes_data = response['Body'].read()
    df = pd.read_csv(io.BytesIO(bytes_data), header=[0, 1], index_col=0)
    # Ajustamos o DataFrame para remover o nível de cabeçalho extra
    df.columns = df.columns.droplevel(1)
    # Ajustamos os nomes das colunas e do índice
    df.columns.name = None
    df.index.name = 'Date'
    df = df.reset_index()
    
    print("Arquivo baixado com sucesso!")
    print("Exibindo as primeiras linhas do DataFrame:")
    print(df.head(1))
except Exception as e:
    print(f"Erro ao baixar o arquivo: {e}")

Baixando arquivo landing/01-07-2026/raw_PETR4.csv do bucket data-extract...
Arquivo baixado com sucesso!
Exibindo as primeiras linhas do DataFrame:
         Date     Close      High       Low      Open    Volume
0  2016-06-30  2.433883  2.451969  2.387375  2.433883  43741300

# Tratamento do dataset
- Como nosso dataset está totalmente limpo, irei aplicar engenharia de feature

In [118]:
df_ef = df.copy()

# Cálculo das médias móveis simples (SMA) para diferentes janelas de tempo em 5, 10, 20 e 30 dias
df_ef["SMA_5"] = df_ef['Close'].rolling(window=5).mean()
df_ef["SMA_15"] = df_ef['Close'].rolling(window=15).mean()
df_ef["SMA_30"] = df_ef['Close'].rolling(window=30).mean()

# Cálculo das médias móveis exponenciais (EMA) para diferentes janelas de tempo em 5, 10, 20 e 30 dias
df_ef["EMA_5"] = df_ef['Close'].ewm(span=5, adjust=False).mean()
df_ef["EMA_15"] = df_ef['Close'].ewm(span=15, adjust=False).mean()
df_ef["EMA_30"] = df_ef['Close'].ewm(span=30, adjust=False).mean()

# Cálculo da variação percentual diária do preço de fechamento e do volume negociado
df_ef['Variation_pct'] = df_ef['Close'].pct_change()
df_ef['Vol_variation_pct'] = df_ef['Volume'].pct_change()
df_ef['Vol_variation_pct_10'] = df_ef['Volume'].pct_change(periods=10)
df_ef.head(30)

,Date,Close,High,Low,Open,Volume,SMA_5,SMA_15,SMA_30,EMA_5,EMA_15,EMA_30,Variation_pct,Vol_variation_pct,Vol_variation_pct_10
0,2016-06-30,2.433883,2.451969,2.387375,2.433883,43741300,NaN,NaN,NaN,2.433883,2.433883,2.433883,NaN,NaN,NaN
1,2016-07-01,2.537231,2.544983,2.420963,2.449384,49290800,NaN,NaN,NaN,2.468332,2.446801,2.440550,0.042462,0.126871,NaN
2,2016-07-04,2.550150,2.596658,2.529481,2.570820,24505100,NaN,NaN,NaN,2.495605,2.459720,2.447621,0.005092,-0.502846,NaN
3,2016-07-05,2.400294,2.498476,2.384792,2.493309,69691200,NaN,NaN,NaN,2.463835,2.452292,2.444568,-0.058764,1.843947,NaN
4,2016-07-06,2.454552,2.459720,2.312446,2.348619,68781500,2.475222,NaN,NaN,2.460741,2.452574,2.445212,0.022605,-0.013053,NaN
5,2016-07-07,2.470055,2.578572,2.459720,2.495892,81610300,2.482457,NaN,NaN,2.463845,2.454759,2.446815,0.006316,0.186515,NaN
6,2016-07-08,2.542400,2.568237,2.498476,2.544983,42647600,2.483490,NaN,NaN,2.490030,2.465714,2.452982,0.029289,-0.477424,NaN
7,2016-07-11,2.676754,2.679337,2.578571,2.583739,66717300,2.508811,NaN,NaN,2.552271,2.492094,2.467419,0.052845,0.564386,NaN
8,2016-07-12,2.751683,2.790439,2.733596,2.741348,58174200,2.579089,NaN,NaN,2.618742,2.524543,2.485758,0.027992,-0.128049,NaN
9,2016-07-13,2.746515,2.746515,2.637998,2.705175,64252100,2.637481,NaN,NaN,2.661333,2.552289,2.502581,-0.001878,0.104478,NaN
10,2016-07-14,2.824027,2.836945,2.754266,2.821443,53059500,2.708275,NaN,NaN,2.715564,2.586256,2.523320,0.028222,-0.174198,0.213030
11,2016-07-15,2.847281,2.857616,2.795606,2.818860,51223500,2.769252,NaN,NaN,2.759470,2.618885,2.544220,0.008234,-0.034603,0.039210
12,2016-07-18,2.984219,3.033310,2.808524,2.834362,77358900,2.830745,NaN,NaN,2.834386,2.664551,2.572607,0.048094,0.510223,2.156849
13,2016-07-19,3.043645,3.092736,2.971300,2.973884,53692000,2.889137,NaN,NaN,2.904139,2.711938,2.602997,0.019913,-0.305936,-0.229573
14,2016-07-20,3.053980,3.074650,2.981635,3.053980,49261200,2.950630,2.687778,NaN,2.954086,2.754693,2.632093,0.003396,-0.082523,-0.283802
15,2016-07-21,3.061731,3.097903,3.030726,3.041061,37748600,2.998171,2.729634,NaN,2.989968,2.793073,2.659811,0.002538,-0.233705,-0.537453
16,2016-07-22,3.084984,3.092735,3.028142,3.059147,33938400,3.045712,2.766151,NaN,3.021640,2.829562,2.687242,0.007595,-0.100936,-0.204213
17,2016-07-25,3.108239,3.165081,3.077234,3.095320,47192000,3.070516,2.803357,NaN,3.050506,2.864396,2.714403,0.007538,0.390519,-0.292657
18,2016-07-26,3.069483,3.118574,3.061731,3.087569,38304800,3.075683,2.847970,NaN,3.056832,2.890032,2.737311,-0.012469,-0.188320,-0.341550
19,2016-07-27,2.973885,3.110823,2.973885,3.097904,51952100,3.059664,2.882592,NaN,3.029183,2.900514,2.752574,-0.031145,0.356282,-0.191433
20,2016-07-28,2.955798,2.984219,2.880870,2.945463,40663100,3.038478,2.914975,NaN,3.004721,2.907424,2.765685,-0.006082,-0.217296,-0.233632
21,2016-07-29,3.066898,3.095319,2.999720,3.038477,60740000,3.034860,2.949941,NaN,3.025447,2.927359,2.785118,0.037587,0.493738,0.185784
22,2016-08-01,2.906706,3.092736,2.898955,3.082401,52012300,2.994554,2.965271,NaN,2.985867,2.924777,2.792963,-0.052232,-0.143689,-0.327649
23,2016-08-02,2.935127,3.002305,2.867950,2.927376,49134600,2.967683,2.977501,NaN,2.968953,2.926071,2.802135,0.009778,-0.055327,-0.084880
24,2016-08-03,3.074649,3.074649,2.927376,2.991970,55695500,2.987836,2.999377,NaN,3.004185,2.944643,2.819716,0.047535,0.133529,0.130616
25,2016-08-04,3.103070,3.131491,3.066898,3.082400,63207500,3.017290,3.017980,NaN,3.037147,2.964446,2.837997,0.009244,0.134876,0.674433
26,2016-08-05,3.010056,3.144411,3.010056,3.131492,54225900,3.005922,3.028831,NaN,3.028117,2.970148,2.849098,-0.029975,-0.142097,0.597774
27,2016-08-08,3.077233,3.092735,3.022974,3.046228,41552000,3.040027,3.035032,NaN,3.044489,2.983533,2.863816,0.022317,-0.233724,-0.119512
28,2016-08-09,3.069483,3.118574,3.035894,3.079818,33596200,3.066898,3.036755,NaN,3.052820,2.994277,2.877085,-0.002519,-0.191466,-0.122925
29,2016-08-10,2.986802,3.092736,2.986802,3.087568,41638400,3.049329,3.032276,2.860027,3.030814,2.993343,2.884163,-0.026936,0.239378,-0.198523

In [119]:
df_ef['Date'] = pd.to_datetime(df_ef['Date'])
# Adicionando colunas para o dia da semana e o mês do ano para o modelo entender padrões sazonais
df_ef["Day_of_week_num"] = df_ef['Date'].dt.weekday
df_ef["Month_num"] = df_ef['Date'].dt.month
df_ef.head(30)

,Date,Close,High,Low,Open,Volume,SMA_5,SMA_15,SMA_30,EMA_5,EMA_15,EMA_30,Variation_pct,Vol_variation_pct,Vol_variation_pct_10,Day_of_week_num,Month_num
0,2016-06-30,2.433883,2.451969,2.387375,2.433883,43741300,NaN,NaN,NaN,2.433883,2.433883,2.433883,NaN,NaN,NaN,3,6
1,2016-07-01,2.537231,2.544983,2.420963,2.449384,49290800,NaN,NaN,NaN,2.468332,2.446801,2.440550,0.042462,0.126871,NaN,4,7
2,2016-07-04,2.550150,2.596658,2.529481,2.570820,24505100,NaN,NaN,NaN,2.495605,2.459720,2.447621,0.005092,-0.502846,NaN,0,7
3,2016-07-05,2.400294,2.498476,2.384792,2.493309,69691200,NaN,NaN,NaN,2.463835,2.452292,2.444568,-0.058764,1.843947,NaN,1,7
4,2016-07-06,2.454552,2.459720,2.312446,2.348619,68781500,2.475222,NaN,NaN,2.460741,2.452574,2.445212,0.022605,-0.013053,NaN,2,7
5,2016-07-07,2.470055,2.578572,2.459720,2.495892,81610300,2.482457,NaN,NaN,2.463845,2.454759,2.446815,0.006316,0.186515,NaN,3,7
6,2016-07-08,2.542400,2.568237,2.498476,2.544983,42647600,2.483490,NaN,NaN,2.490030,2.465714,2.452982,0.029289,-0.477424,NaN,4,7
7,2016-07-11,2.676754,2.679337,2.578571,2.583739,66717300,2.508811,NaN,NaN,2.552271,2.492094,2.467419,0.052845,0.564386,NaN,0,7
8,2016-07-12,2.751683,2.790439,2.733596,2.741348,58174200,2.579089,NaN,NaN,2.618742,2.524543,2.485758,0.027992,-0.128049,NaN,1,7
9,2016-07-13,2.746515,2.746515,2.637998,2.705175,64252100,2.637481,NaN,NaN,2.661333,2.552289,2.502581,-0.001878,0.104478,NaN,2,7
10,2016-07-14,2.824027,2.836945,2.754266,2.821443,53059500,2.708275,NaN,NaN,2.715564,2.586256,2.523320,0.028222,-0.174198,0.213030,3,7
11,2016-07-15,2.847281,2.857616,2.795606,2.818860,51223500,2.769252,NaN,NaN,2.759470,2.618885,2.544220,0.008234,-0.034603,0.039210,4,7
12,2016-07-18,2.984219,3.033310,2.808524,2.834362,77358900,2.830745,NaN,NaN,2.834386,2.664551,2.572607,0.048094,0.510223,2.156849,0,7
13,2016-07-19,3.043645,3.092736,2.971300,2.973884,53692000,2.889137,NaN,NaN,2.904139,2.711938,2.602997,0.019913,-0.305936,-0.229573,1,7
14,2016-07-20,3.053980,3.074650,2.981635,3.053980,49261200,2.950630,2.687778,NaN,2.954086,2.754693,2.632093,0.003396,-0.082523,-0.283802,2,7
15,2016-07-21,3.061731,3.097903,3.030726,3.041061,37748600,2.998171,2.729634,NaN,2.989968,2.793073,2.659811,0.002538,-0.233705,-0.537453,3,7
16,2016-07-22,3.084984,3.092735,3.028142,3.059147,33938400,3.045712,2.766151,NaN,3.021640,2.829562,2.687242,0.007595,-0.100936,-0.204213,4,7
17,2016-07-25,3.108239,3.165081,3.077234,3.095320,47192000,3.070516,2.803357,NaN,3.050506,2.864396,2.714403,0.007538,0.390519,-0.292657,0,7
18,2016-07-26,3.069483,3.118574,3.061731,3.087569,38304800,3.075683,2.847970,NaN,3.056832,2.890032,2.737311,-0.012469,-0.188320,-0.341550,1,7
19,2016-07-27,2.973885,3.110823,2.973885,3.097904,51952100,3.059664,2.882592,NaN,3.029183,2.900514,2.752574,-0.031145,0.356282,-0.191433,2,7
20,2016-07-28,2.955798,2.984219,2.880870,2.945463,40663100,3.038478,2.914975,NaN,3.004721,2.907424,2.765685,-0.006082,-0.217296,-0.233632,3,7
21,2016-07-29,3.066898,3.095319,2.999720,3.038477,60740000,3.034860,2.949941,NaN,3.025447,2.927359,2.785118,0.037587,0.493738,0.185784,4,7
22,2016-08-01,2.906706,3.092736,2.898955,3.082401,52012300,2.994554,2.965271,NaN,2.985867,2.924777,2.792963,-0.052232,-0.143689,-0.327649,0,8
23,2016-08-02,2.935127,3.002305,2.867950,2.927376,49134600,2.967683,2.977501,NaN,2.968953,2.926071,2.802135,0.009778,-0.055327,-0.084880,1,8
24,2016-08-03,3.074649,3.074649,2.927376,2.991970,55695500,2.987836,2.999377,NaN,3.004185,2.944643,2.819716,0.047535,0.133529,0.130616,2,8
25,2016-08-04,3.103070,3.131491,3.066898,3.082400,63207500,3.017290,3.017980,NaN,3.037147,2.964446,2.837997,0.009244,0.134876,0.674433,3,8
26,2016-08-05,3.010056,3.144411,3.010056,3.131492,54225900,3.005922,3.028831,NaN,3.028117,2.970148,2.849098,-0.029975,-0.142097,0.597774,4,8
27,2016-08-08,3.077233,3.092735,3.022974,3.046228,41552000,3.040027,3.035032,NaN,3.044489,2.983533,2.863816,0.022317,-0.233724,-0.119512,0,8
28,2016-08-09,3.069483,3.118574,3.035894,3.079818,33596200,3.066898,3.036755,NaN,3.052820,2.994277,2.877085,-0.002519,-0.191466,-0.122925,1,8
29,2016-08-10,2.986802,3.092736,2.986802,3.087568,41638400,3.049329,3.032276,2.860027,3.030814,2.993343,2.884163,-0.026936,0.239378,-0.198523,2,8

- Vamos adicionar a métrica de RSI ao dataset

In [120]:
periodo = 14
# Calculando o ganho e a perda entre o dia atual e o dia anterior
df_ef['Delta'] = df_ef['Close'].diff()
# Separamos os ganhos e perdas em colunas distintas, substituindo valores negativos por 0 na coluna de ganhos e valores positivos por 0 na coluna de perdas
df_ef['Ganho'] = df_ef['Delta'].where(df_ef['Delta'] > 0, 0)
df_ef['Perda'] = df_ef['Delta'].where(df_ef['Delta'] < 0, 0).abs()
# Calculamos a média movel exponencial (EMA) dos ganhos e perdas para suavizar os valores e obter uma visão mais clara da tendência de alta ou baixa do ativo
df_ef['Media_ganho'] = df_ef['Ganho'].ewm(alpha=1/periodo, adjust=False).mean()
df_ef['Media_perda'] = df_ef['Perda'].ewm(alpha=1/periodo, adjust=False).mean()

# Cálculo do Índice de Força Relativa (RSI) com base nas médias móveis exponenciais dos ganhos e perdas
df_ef['RS'] = df_ef['Media_ganho'] / df_ef['Media_perda']
df_ef['RSI'] = 100 - (100 / (1 + df_ef['RS']))

# Removendo colunas desnecessárias do DataFrame
df_ef = df_ef.drop(columns=['Delta', 'Ganho', 'Perda', 'Media_ganho', 'Media_perda', 'RS'])
# Retirada de valores nulos do DataFrame resultante
df_ef.dropna(inplace=True)

df_ef.head(30)

,Date,Close,High,Low,Open,Volume,SMA_5,SMA_15,SMA_30,EMA_5,EMA_15,EMA_30,Variation_pct,Vol_variation_pct,Vol_variation_pct_10,Day_of_week_num,Month_num,RSI
29,2016-08-10,2.986802,3.092736,2.986802,3.087568,41638400,3.049329,3.032276,2.860027,3.030814,2.993343,2.884163,-0.026936,0.239378,-0.198523,2,8,55.523505
30,2016-08-11,3.126324,3.126324,2.997137,3.004888,55881500,3.053979,3.036582,2.883108,3.062651,3.009965,2.899787,0.046713,0.342066,0.374256,3,8,62.574738
31,2016-08-12,3.100487,3.214172,3.095320,3.113406,71281300,3.072066,3.037616,2.901884,3.075263,3.021281,2.912735,-0.008264,0.275580,0.173548,4,8,60.656972
32,2016-08-15,3.180584,3.196086,3.118574,3.149579,53568000,3.092736,3.042439,2.922898,3.110370,3.041193,2.930016,0.025834,-0.248499,0.029910,0,8,64.308864
33,2016-08-16,3.227090,3.245176,3.136659,3.180583,48218700,3.124257,3.052946,2.950458,3.149276,3.064430,2.949182,0.014622,-0.099860,-0.018641,1,8,66.266752
34,2016-08-17,3.296850,3.296850,3.183166,3.221922,46809100,3.186267,3.074477,2.978534,3.198468,3.093483,2.971612,0.021617,-0.029233,-0.159553,2,8,69.012730
35,2016-08-18,3.327857,3.366613,3.302019,3.307187,44941100,3.226574,3.099281,3.007128,3.241597,3.122780,2.994595,0.009405,-0.039907,-0.288991,3,8,70.174848
36,2016-08-19,3.304602,3.338190,3.281348,3.312353,33360000,3.267396,3.115128,3.032535,3.262599,3.145507,3.014596,-0.006988,-0.257695,-0.384796,4,8,68.111665
37,2016-08-22,3.190918,3.263263,3.177999,3.263263,43258900,3.269463,3.134075,3.049673,3.238705,3.151184,3.025971,-0.034402,0.296730,0.041079,0,8,58.982285
38,2016-08-23,3.273598,3.322689,3.209004,3.224507,61048000,3.278765,3.156640,3.067071,3.250336,3.166485,3.041947,0.025911,0.411224,0.817110,1,8,62.879212
39,2016-08-24,3.203836,3.283932,3.196085,3.229673,44694700,3.260162,3.165253,3.082315,3.234836,3.171154,3.052392,-0.021310,-0.267876,0.073401,2,8,57.882294
40,2016-08-25,3.237425,3.265846,3.190918,3.209004,40290500,3.242076,3.174210,3.096095,3.235699,3.179438,3.064329,0.010484,-0.098540,-0.279001,3,8,59.549110
41,2016-08-26,3.242592,3.333023,3.216755,3.278765,50650500,3.229674,3.189712,3.109272,3.237997,3.187332,3.075830,0.001596,0.257133,-0.289428,4,8,59.812609
42,2016-08-29,3.325272,3.348525,3.216755,3.229673,36990100,3.256544,3.206248,3.120640,3.267088,3.204575,3.091923,0.025498,-0.269699,-0.309474,0,8,63.868095
43,2016-08-30,3.382115,3.418287,3.351110,3.369196,51893700,3.278248,3.227090,3.131922,3.305431,3.226767,3.110645,0.017094,0.402908,0.076215,1,8,66.380089
44,2016-08-31,3.320106,3.415704,3.283933,3.392450,61016100,3.301502,3.249310,3.140793,3.310322,3.238435,3.124159,-0.018334,0.175790,0.303509,2,8,61.367874
45,2016-09-01,3.358861,3.382114,3.296851,3.351110,45370000,3.325789,3.264813,3.150698,3.326502,3.253488,3.139301,0.011673,-0.256426,0.009544,3,9,63.236259
46,2016-09-02,3.506134,3.508718,3.397617,3.415704,57017000,3.378498,3.291856,3.164736,3.386379,3.285069,3.162968,0.043846,0.256711,0.709143,4,9,69.310473
47,2016-09-05,3.573313,3.599150,3.547475,3.562978,26292200,3.428106,3.318038,3.180238,3.448690,3.321099,3.189441,0.019160,-0.538871,-0.392213,0,9,71.614344
48,2016-09-06,3.612067,3.612067,3.495799,3.537139,42086900,3.474096,3.343703,3.198325,3.503149,3.357470,3.216708,0.010846,0.600737,-0.310593,1,9,72.879219
49,2016-09-08,3.674079,3.692165,3.606902,3.635323,42797300,3.544891,3.368852,3.221664,3.560126,3.397046,3.246215,0.017168,0.016879,-0.042452,3,9,74.813233
50,2016-09-09,3.490631,3.622402,3.490631,3.606900,43155300,3.571245,3.379703,3.239492,3.536961,3.408744,3.261984,-0.049930,0.008365,0.071104,4,9,60.963313
51,2016-09-12,3.604317,3.604317,3.428623,3.441541,44141000,3.590881,3.399684,3.257406,3.559413,3.433191,3.284070,0.032569,0.022841,-0.128518,0,9,65.255979
52,2016-09-13,3.361445,3.578479,3.343359,3.539723,64134000,3.548508,3.411053,3.272564,3.493424,3.424223,3.289062,-0.067384,0.452935,0.733815,1,9,52.080028
53,2016-09-14,3.387282,3.451875,3.351109,3.397617,43932500,3.503551,3.418632,3.287636,3.458043,3.419605,3.295399,0.007686,-0.314989,-0.153414,2,9,53.163433
54,2016-09-15,3.490631,3.503550,3.400200,3.413119,42169100,3.466861,3.437751,3.301502,3.468906,3.428483,3.307995,0.030511,-0.040139,-0.308886,3,9,57.320182
55,2016-09-16,3.400202,3.467379,3.400202,3.446709,44651900,3.448775,3.448603,3.311406,3.446004,3.424948,3.313943,-0.025906,0.058877,-0.015828,4,9,52.896512
56,2016-09-19,3.371780,3.498383,3.364029,3.467378,51105500,3.402268,3.457216,3.323464,3.421263,3.418302,3.317675,-0.008359,0.144531,-0.103680,0,9,51.549962
57,2016-09-20,3.488049,3.521637,3.444125,3.475130,52063100,3.427589,3.468067,3.337158,3.443525,3.427020,3.328667,0.034483,0.018738,0.980173,1,9,56.435667
58,2016-09-21,3.529388,3.537139,3.462211,3.513886,61094100,3.456010,3.477886,3.352488,3.472146,3.439816,3.341616,0.011852,0.173463,0.451618,2,9,58.055230

In [121]:
df_ef.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2462 entries, 29 to 2490
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  2462 non-null   datetime64[ns]
 1   Close                 2462 non-null   float64
 2   High                  2462 non-null   float64
 3   Low                   2462 non-null   float64
 4   Open                  2462 non-null   float64
 5   Volume                2462 non-null   int64
 6   SMA_5                 2462 non-null   float64
 7   SMA_15                2462 non-null   float64
 8   SMA_30                2462 non-null   float64
 9   EMA_5                 2462 non-null   float64
 10  EMA_15                2462 non-null   float64
 11  EMA_30                2462 non-null   float64
 12  Variation_pct         2462 non-null   float64
 13  Vol_variation_pct     2462 non-null   float64
 14  Vol_variation_pct_10  2462 non-null   float64
 15  Day_of_week_num       2462 non-null   int32
 16  Month_num             2462 non-null   int32
 17  RSI                   2462 non-null   float64
dtypes: datetime64[ns](1), float64(14), int32(2), int64(1)
memory usage: 346.2 KB

In [122]:
df_ef.describe()

,Date,Close,High,Low,Open,Volume,SMA_5,SMA_15,SMA_30,EMA_5,EMA_15,EMA_30,Variation_pct,Vol_variation_pct,Vol_variation_pct_10,Day_of_week_num,Month_num,RSI
count,2462,2462.000000,2462.000000,2462.000000,2462.000000,2.462000e+03,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000,2462.000000
mean,2021-07-19 02:10:25.832656384,14.507764,14.688275,14.326781,14.507776,5.731829e+07,14.479367,14.406779,14.291924,14.479216,14.404924,14.285972,0.001362,inf,inf,1.998375,6.499594,54.252505
min,2016-08-10 00:00:00,2.986802,3.092736,2.986802,3.004888,0.000000e+00,3.049329,3.032276,2.860027,3.030814,2.993343,2.884163,-0.296978,-1.000000,-1.000000,0.000000,1.000000,16.966736
25%,2019-01-28 06:00:00,5.798445,5.884223,5.710678,5.813398,3.547318e+07,5.797228,5.759714,5.727603,5.792549,5.763252,5.720273,-0.010415,-0.232293,-0.294564,1.000000,4.000000,45.883150
50%,2021-07-22 12:00:00,8.279569,8.397094,8.167609,8.291711,4.992425e+07,8.265964,8.195806,8.179417,8.251492,8.208371,8.145409,0.001280,-0.015853,-0.017931,2.000000,6.500000,54.340688
75%,2024-01-10 18:00:00,26.101257,26.443049,25.799240,26.095929,6.930145e+07,25.957001,26.096047,25.734812,26.083197,26.392101,26.021434,0.013712,0.291020,0.403730,3.000000,9.000000,62.609798
max,2026-06-30 00:00:00,48.523716,49.157930,48.110663,48.556670,4.902304e+08,47.906105,46.899001,46.782045,47.832550,47.108034,46.039362,0.222222,inf,inf,4.000000,12.000000,88.396233
std,NaN,11.293236,11.398614,11.180101,11.285214,3.358626e+07,11.273818,11.221680,11.128476,11.271037,11.209253,11.098343,0.025842,NaN,NaN,1.411336,3.437578,12.251503

In [123]:
df_clean = df_ef.copy()
df_clean = df_clean.drop(columns=['High', 'Low', 'Open'])
df_clean = df_clean[['Date', 'Close', 'Variation_pct', 'SMA_5', 'SMA_15', 'SMA_30', 'EMA_5', 'EMA_15', 'EMA_30', 'RSI', 'Volume', 'Vol_variation_pct', 'Vol_variation_pct_10', 'Day_of_week_num', 'Month_num',]]
df_clean.head(30)

,Date,Close,Variation_pct,SMA_5,SMA_15,SMA_30,EMA_5,EMA_15,EMA_30,RSI,Volume,Vol_variation_pct,Vol_variation_pct_10,Day_of_week_num,Month_num
29,2016-08-10,2.986802,-0.026936,3.049329,3.032276,2.860027,3.030814,2.993343,2.884163,55.523505,41638400,0.239378,-0.198523,2,8
30,2016-08-11,3.126324,0.046713,3.053979,3.036582,2.883108,3.062651,3.009965,2.899787,62.574738,55881500,0.342066,0.374256,3,8
31,2016-08-12,3.100487,-0.008264,3.072066,3.037616,2.901884,3.075263,3.021281,2.912735,60.656972,71281300,0.275580,0.173548,4,8
32,2016-08-15,3.180584,0.025834,3.092736,3.042439,2.922898,3.110370,3.041193,2.930016,64.308864,53568000,-0.248499,0.029910,0,8
33,2016-08-16,3.227090,0.014622,3.124257,3.052946,2.950458,3.149276,3.064430,2.949182,66.266752,48218700,-0.099860,-0.018641,1,8
34,2016-08-17,3.296850,0.021617,3.186267,3.074477,2.978534,3.198468,3.093483,2.971612,69.012730,46809100,-0.029233,-0.159553,2,8
35,2016-08-18,3.327857,0.009405,3.226574,3.099281,3.007128,3.241597,3.122780,2.994595,70.174848,44941100,-0.039907,-0.288991,3,8
36,2016-08-19,3.304602,-0.006988,3.267396,3.115128,3.032535,3.262599,3.145507,3.014596,68.111665,33360000,-0.257695,-0.384796,4,8
37,2016-08-22,3.190918,-0.034402,3.269463,3.134075,3.049673,3.238705,3.151184,3.025971,58.982285,43258900,0.296730,0.041079,0,8
38,2016-08-23,3.273598,0.025911,3.278765,3.156640,3.067071,3.250336,3.166485,3.041947,62.879212,61048000,0.411224,0.817110,1,8
39,2016-08-24,3.203836,-0.021310,3.260162,3.165253,3.082315,3.234836,3.171154,3.052392,57.882294,44694700,-0.267876,0.073401,2,8
40,2016-08-25,3.237425,0.010484,3.242076,3.174210,3.096095,3.235699,3.179438,3.064329,59.549110,40290500,-0.098540,-0.279001,3,8
41,2016-08-26,3.242592,0.001596,3.229674,3.189712,3.109272,3.237997,3.187332,3.075830,59.812609,50650500,0.257133,-0.289428,4,8
42,2016-08-29,3.325272,0.025498,3.256544,3.206248,3.120640,3.267088,3.204575,3.091923,63.868095,36990100,-0.269699,-0.309474,0,8
43,2016-08-30,3.382115,0.017094,3.278248,3.227090,3.131922,3.305431,3.226767,3.110645,66.380089,51893700,0.402908,0.076215,1,8
44,2016-08-31,3.320106,-0.018334,3.301502,3.249310,3.140793,3.310322,3.238435,3.124159,61.367874,61016100,0.175790,0.303509,2,8
45,2016-09-01,3.358861,0.011673,3.325789,3.264813,3.150698,3.326502,3.253488,3.139301,63.236259,45370000,-0.256426,0.009544,3,9
46,2016-09-02,3.506134,0.043846,3.378498,3.291856,3.164736,3.386379,3.285069,3.162968,69.310473,57017000,0.256711,0.709143,4,9
47,2016-09-05,3.573313,0.019160,3.428106,3.318038,3.180238,3.448690,3.321099,3.189441,71.614344,26292200,-0.538871,-0.392213,0,9
48,2016-09-06,3.612067,0.010846,3.474096,3.343703,3.198325,3.503149,3.357470,3.216708,72.879219,42086900,0.600737,-0.310593,1,9
49,2016-09-08,3.674079,0.017168,3.544891,3.368852,3.221664,3.560126,3.397046,3.246215,74.813233,42797300,0.016879,-0.042452,3,9
50,2016-09-09,3.490631,-0.049930,3.571245,3.379703,3.239492,3.536961,3.408744,3.261984,60.963313,43155300,0.008365,0.071104,4,9
51,2016-09-12,3.604317,0.032569,3.590881,3.399684,3.257406,3.559413,3.433191,3.284070,65.255979,44141000,0.022841,-0.128518,0,9
52,2016-09-13,3.361445,-0.067384,3.548508,3.411053,3.272564,3.493424,3.424223,3.289062,52.080028,64134000,0.452935,0.733815,1,9
53,2016-09-14,3.387282,0.007686,3.503551,3.418632,3.287636,3.458043,3.419605,3.295399,53.163433,43932500,-0.314989,-0.153414,2,9
54,2016-09-15,3.490631,0.030511,3.466861,3.437751,3.301502,3.468906,3.428483,3.307995,57.320182,42169100,-0.040139,-0.308886,3,9
55,2016-09-16,3.400202,-0.025906,3.448775,3.448603,3.311406,3.446004,3.424948,3.313943,52.896512,44651900,0.058877,-0.015828,4,9
56,2016-09-19,3.371780,-0.008359,3.402268,3.457216,3.323464,3.421263,3.418302,3.317675,51.549962,51105500,0.144531,-0.103680,0,9
57,2016-09-20,3.488049,0.034483,3.427589,3.468067,3.337158,3.443525,3.427020,3.328667,56.435667,52063100,0.018738,0.980173,1,9
58,2016-09-21,3.529388,0.011852,3.456010,3.477886,3.352488,3.472146,3.439816,3.341616,58.055230,61094100,0.173463,0.451618,2,9

## Vamos efetuar a normalização dos dados
- Vou utilizar o MimMaxScaler com dados sendo criados entre -1 a 1

In [124]:
df_clean = df_clean.replace([np.inf, -np.inf], np.nan)
df_clean = df_clean.dropna()

target = df_clean['Close']
features = df_clean.drop(columns=['Date'])


scaler_target = MinMaxScaler(feature_range=(0, 1))
target_normalized = scaler_target.fit_transform(target.values.reshape(-1, 1))

scaler_all = MinMaxScaler(feature_range=(0, 1))
data_normalized = scaler_all.fit_transform(features)

In [ ]:
def sliding_window(data, window_size: int) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Creates sliding windows from the data for time series forecasting.
    Parameters:
    - data: Numpy array of shape (num_samples, num_features).
    - window_size: Size of the sliding window.
    Returns:
    - Tuple of tensors (X, y) where X is the input windows and y is the target values.
    """
    
    X = []
    y = []
    
    # Loop que percorre os dados criando fotos do passado
    for i in range(len(data) - window_size):
        window = data[i:(i + window_size)]
        
        target = data[i + window_size]

        target_value = target[0]
        
        X.append(window)
        y.append(target_value)
        
    return torch.tensor(np.array(X).astype(np.float32)), torch.tensor(np.array(y).astype(np.float32))

X_tensor, y_tensor = sliding_window(data_normalized, window_size=15)

# Dividindo em treino e teste (80% treino, 20% teste)
train_size = int(len(X_tensor) * 0.8)
X_train = X_tensor[:train_size]
y_train = y_tensor[:train_size]
X_test = X_tensor[train_size:]
y_test = y_tensor[train_size:]